markocupic_sac_event_feedback:
  configs:
    # Default configuration
    default:
      name: 'default'
      # Allow Allow feedbacks up to 10 days after event end date
      feedback_expiration_time: 60 #days
      # Send reminders: 1 day after event end
      # Send reminders: 14 days after event end
      # Send reminders: 28 days after event end
      send_reminder_after_days: [1,14,28] #days

