services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            #Symfony\Component\HttpKernel\UriSigner: '@uri_signer'
            #Contao\CoreBundle\Security\User\UserChecker: '@contao.security.user_checker'

    Markocupic\SacEventEvaluation\:
        resource: ../../
        exclude: ../../{DependencyInjection,Resources,Model}

