services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $onlineFeedbackConfigs: '%markocupic_sac_event_feedback.configs%'

    Markocupic\SacEventFeedback\:
        resource: ../../
        exclude: ../../{DependencyInjection,Resources,Model}
