services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $onlineFeedbackConfigs: '%markocupic_sac_event_feedback.configs%'

    Markocupic\SacEventFeedback\:
        resource: ../../
        exclude: ../../{DependencyInjection,Resources,Model}

    Markocupic\SacEventFeedback\EventListener\ContaoHooks\StoreFormDataListener:
        tags:
            - { name: contao.hook, hook: storeFormData, method: augmentData, priority: 0 }

    Markocupic\SacEventFeedback\EventListener\ContaoHooks\PrepareFormDataListener:
        tags:
            - { name: contao.hook, hook: prepareFormData, method: prepareFormData, priority: 0 }