services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $onlineEvaluationConfigs: '%markocupic_sac_event_evaluation.configs%'

    Markocupic\SacEventEvaluation\:
        resource: ../../
        exclude: ../../{DependencyInjection,Resources,Model}

