services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $onlineFeedbackConfigs: '%markocupic_sac_event_feedback.configs%'
            $secret: '%markocupic_sac_event_feedback.secret%'

    Markocupic\SacEventFeedback\:
        resource: ../../
        exclude: ../../{DependencyInjection,Resources,Model}

    Markocupic\SacEventFeedback\Contao\Controller\EventFeedbackController:
        public: true
