services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $projectDir: '%kernel.project_dir%'
            $feedbackConfig: '%markocupic_sac_event_feedback.configs%'
            $deleteFeedbacksAfter: '%markocupic_sac_event_feedback.delete_feedbacks_after%'
            $docxTemplate: '%markocupic_sac_event_feedback.docx_template%'
            $secret: '%markocupic_sac_event_feedback.secret%'

    Markocupic\SacEventFeedback\:
        resource: ../src/
        exclude: ../src/{DependencyInjection,Model}

    # Controller
    Markocupic\SacEventFeedback\Contao\Controller\EventFeedbackController:
        public: true

    # Add a session bag
    Markocupic\SacEventFeedback\Session\Attribute\ArrayAttributeBag:
        arguments:
            - '_markocupic_sac_event_feedback_attributes'
        calls:
            - [ setName, [ 'markocupic_sac_event_feedback' ] ]
